bankWebApp:
  db:
    url: jdbc:h2:mem:myBank

  liquibase:
    contexts: local

h2:
  console:
    enabled: true

springdoc:
  show-login-endpoint: true


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
