spring:
  application:
    name: bankWebApp
  security:
    user:
      name: ${bankWebApp.security.user.name:}
      password: ${bankWebApp.security.user.password:}
  profiles:
    include:
#      - prod
      - local
  datasource:
    url: ${bankWebApp.db.url}
    username: ${bankWebApp.db.username:}
    password: ${bankWebApp.db.password:}
  liquibase:
    contexts: ${bankWebApp.liquibase.contexts:}
  h2:
    console:  
      enabled: ${h2.console.enabled:false}
  jpa:
    hibernate:
      ddl-auto: update # make this property none if you want to retain your data in the database
logging:
  level:
    sql: debug
#    web: debug

server:
  port: 9080